#!/usr/bin/env bash

# Redirect all calls to `node` to the instrumented version of Node.

# INVARIANT: this script expects the following environment variables to be
#            set:
#            - $NODEPROF_HOME --> path to NodeProf installation
#            - $NODEPROF_ANALYSIS_PATH --> path to NodeProf analysis to be used

# Get directory of THIS script. This will be used to execute
# the `check-env-vars` script, which should be located in
# the same directory as this script.
SCRIPT_DIRECTORY="$(dirname ${BASH_SOURCE[0]})"

# ensure environment variables are set
$SCRIPT_DIRECTORY/check-env-vars

echo 'Intercepted invocation of `node`! Instrumenting call...'


mx -v -p $NODEPROF_HOME jalangi --analysis $NODEPROF_ANALYSIS_PATH $@
