#!/usr/bin/env bash

# Redirect all calls to `node` to the instrumented version of Node.

# INVARIANT: this script expects the following environment variables to be
#            set:
#            - $NODEPROF_ANALYSIS_PATH --> path of the analysis
#            - $NODEPROF_JALANGI_PATH  --> path to jalangi.js file (see repo)
#            - $GRAALJS_EXECUTABLE     --> path to GraalJS's `node` executable

# Get directory of THIS script. This will be used to execute
# the `check-env-vars` script, which should be located in
# the same directory as this script.
SCRIPT_DIRECTORY="$(dirname ${BASH_SOURCE[0]})"

# ensure environment variables are set
$SCRIPT_DIRECTORY/check-env-vars

echo 'Intercepted invocation of `node`! Instrumenting call...'

$GRAALJS_EXECUTABLE --jvm --vm.ea --experimental-options --engine.InstrumentExceptionsAreThrown=true --nodeprof --nodeprof.Analysis=NodeProfJalangi --nodeprof.Scope=module --nodeprof.ExcludeSource=${NODEPROF_ANALYSIS_PATH} ${NODEPROF_JALANGIPATH} --analysis $NODEPROF_ANALYSIS_PATH $@
